[package]
edition = "2021"
name = "pragmatic-segmenter-bindings"
version = "0.0.6"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"
pragmatic-segmenter = "0.1.2"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
